/**
 * ONI // RESEARCH SECTION
 *
 * Three modes:
 *   QUICK STUDY  — research-tuned chat with live "what's happening" panel
 *   DEEP RESEARCH — multi-round council pipeline with PDF export
 *   BRAIN        — ChromaDB memory viewer with RAG explainer
 */

import { useState, useRef, useEffect, useContext, useCallback } from "react";

// ─── COUNCIL ROLES ───────────────────────────────────────────────────
const COUNCIL_ROLES = [
  {
    id: "researcher",
    name: "RESEARCHER",
    icon: "🔬",
    color: "yellow",
    prompt: (topic, round, history, searchEnabled) => `You are a rigorous researcher. Your job is to find and summarize key information about the topic below.
${searchEnabled ? "Search for recent sources and cite them." : "Draw on your training knowledge thoroughly."}
Be factual, thorough, and cite specific claims. Avoid vague generalities.
${history.length ? `\nPrevious findings:\n${history.map(h=>`[${h.role}]: ${h.summary}`).join('\n')}` : ""}
Topic: ${topic}
Round ${round}: Gather key facts, evidence, and sources.`,
  },
  {
    id: "critic",
    name: "CRITIC",
    icon: "⚔️",
    color: "pink",
    prompt: (topic, round, history) => `You are a critical analyst. Your job is to challenge, stress-test, and find gaps in the research below.
Look for: unsupported claims, missing perspectives, potential biases, logical gaps.
Be specific about what's weak and why. Suggest what's missing.
Previous findings:\n${history.map(h=>`[${h.role}]: ${h.summary}`).join('\n')}
Topic: ${topic}
Round ${round}: What are the weaknesses and gaps in this research?`,
  },
  {
    id: "synthesizer",
    name: "SYNTHESIZER",
    icon: "⚡",
    color: "cyan",
    prompt: (topic, round, history) => `You are a synthesis expert. Your job is to integrate all findings and critiques into a coherent, balanced picture.
Resolve contradictions. Build a unified narrative. Highlight key insights.
All findings so far:\n${history.map(h=>`[${h.role}]: ${h.summary}`).join('\n')}
Topic: ${topic}
Round ${round}: Synthesize everything into a clear, structured summary.`,
  },
  {
    id: "archivist",
    name: "ARCHIVIST",
    icon: "📜",
    color: "green",
    prompt: (topic, round, history) => `You are an archivist. Extract the most important facts, concepts, and insights from the research below.
Format as a structured list of discrete, self-contained facts suitable for long-term memory storage.
Each fact should be: specific, verifiable, and stand alone without context.
All findings:\n${history.map(h=>`[${h.role}]: ${h.summary}`).join('\n')}
Topic: ${topic}
Round ${round}: Extract 5-10 key facts/concepts worth remembering permanently.`,
  },
];

// ─── QUICK STUDY SYSTEM PROMPT ────────────────────────────────────────
const QUICK_STUDY_PROMPT = `You are a research assistant optimized for learning and study.
Your responses should:
- Be accurate and cite specific facts
- Explain concepts clearly, building from fundamentals
- Offer to go deeper on any point
- Flag when something is contested or uncertain
- Suggest related concepts worth exploring
Keep responses focused but thorough. Prefer depth over breadth.`;

// ─── PDF GENERATION ───────────────────────────────────────────────────
async function generatePDF(topic, rounds, modelName) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" });
  const margin = 20;
  const pageW  = doc.internal.pageSize.getWidth();
  const pageH  = doc.internal.pageSize.getHeight();
  let y = margin;

  const addText = (text, size=10, bold=false, color=[0,0,0]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, pageW - margin*2);
    lines.forEach(line => {
      if (y > pageH - margin) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += size * 0.45;
    });
    y += 3;
  };

  const addDivider = () => {
    doc.setDrawColor(57,255,20);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageW-margin, y);
    y += 5;
  };

  // Header
  doc.setFillColor(5,5,5);
  doc.rect(0,0,pageW,30,"F");
  addText("ONI // RESEARCH REPORT", 18, true, [57,255,20]);
  addText(`Topic: ${topic}`, 12, false, [200,200,200]);
  addText(`Model: ${modelName}  •  Generated: ${new Date().toLocaleString()}`, 9, false, [120,120,120]);
  addDivider();

  rounds.forEach((round, i) => {
    const role = COUNCIL_ROLES.find(r=>r.id===round.roleId);
    addText(`ROUND ${i+1} — ${role?.name || round.roleId}`, 13, true, [232,255,0]);
    addText(round.content, 10, false, [40,40,40]);
    addDivider();
  });

  addText("Generated by ONI AI Operating System", 8, false, [150,150,150]);
  addText("Running locally — no data sent to external servers", 8, false, [150,150,150]);

  doc.save(`ONI_Research_${topic.replace(/\s+/g,"_").slice(0,30)}_${Date.now()}.pdf`);
}

// ─── MAIN COMPONENT ───────────────────────────────────────────────────
export default function ResearchTab({ goSettings, appCtx }) {
  const [mode, setMode] = useState("quick");
  const { connections, assignments } = appCtx || {};
  const assign = assignments?.research || assignments?.chat;
  const conn   = connections?.find(c=>c.id===assign?.connectionId);

  return (
    <div className="tab-research-v2">
      {/* MODE SWITCHER */}
      <div className="research-modebar">
        <div className="research-modebar-left">
          <div className="tab-title yellow">RESEARCH</div>
          <div className="tab-sub">// STUDY · DISCOVER · REMEMBER</div>
        </div>
        <div className="research-mode-tabs">
          {[
            { id:"quick",  label:"QUICK STUDY",   icon:"📖" },
            { id:"deep",   label:"DEEP RESEARCH",  icon:"🔬" },
            { id:"brain",  label:"BRAIN / MEMORY", icon:"🧠" },
          ].map(m=>(
            <button key={m.id} className={`rmode-btn${mode===m.id?" active":""}`} onClick={()=>setMode(m.id)}>
              <span>{m.icon}</span>{m.label}
            </button>
          ))}
        </div>
        <div className="research-model-indicator">
          {assign?.model
            ? <span className="model-chip yellow">{conn?.icon} {assign.model}</span>
            : <button className="model-chip-empty" onClick={goSettings}>⚙ SET MODEL</button>
          }
        </div>
      </div>

      {/* CONTENT */}
      <div className="research-content">
        {mode==="quick"  && <QuickStudy  conn={conn} assign={assign} goSettings={goSettings} />}
        {mode==="deep"   && <DeepResearch conn={conn} assign={assign} goSettings={goSettings} />}
        {mode==="brain"  && <BrainMemory  conn={conn} assign={assign} goSettings={goSettings} />}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════
// QUICK STUDY
// ═══════════════════════════════════════════════════════════════════
function QuickStudy({ conn, assign, goSettings }) {
  const [messages, setMessages] = useState([
    { role:"ai", text:"Research mode active. Ask me anything — I'll go deep.", tokens:0 }
  ]);
  const [input,      setInput]      = useState("");
  const [streaming,  setStreaming]   = useState(false);
  const [happening,  setHappening]  = useState(null);
  const [tokenCount, setTokenCount] = useState(0);
  const [saveQueue,  setSaveQueue]  = useState([]);
  const endRef    = useRef(null);
  const abortRef  = useRef(null);

  useEffect(()=>{ endRef.current?.scrollIntoView({behavior:"smooth"}); },[messages]);

  const send = async () => {
    const text = input.trim();
    if (!text || streaming) return;
    setInput("");
    setMessages(m=>[...m,{role:"user",text}]);
    setStreaming(true);
    setHappening({ phase:"thinking", model:assign?.model, local:conn?.type==="local" });

    if (!conn || !assign?.model) {
      setMessages(m=>[...m,{role:"ai",text:"⚠ No model configured. Open Settings → Section Defaults."}]);
      setStreaming(false); return;
    }

    const history = messages.slice(-8).map(m=>({ role:m.role==="user"?"user":"assistant", content:m.text }));

    try {
      const endpoint = conn.type==="local"
        ? `${conn.url}/v1/chat/completions`
        : `${conn.url}/chat/completions`;

      abortRef.current = new AbortController();
      const res = await fetch(endpoint, {
        method:"POST", signal: abortRef.current.signal,
        headers:{ "Content-Type":"application/json", ...(conn.apiKey?{"Authorization":`Bearer ${conn.apiKey}`}:{}) },
        body: JSON.stringify({
          model: assign.model,
          messages:[
            { role:"system", content:QUICK_STUDY_PROMPT },
            ...history,
            { role:"user", content:text }
          ],
          stream:true, temperature:0.7,
        }),
      });

      if (!res.ok) throw new Error(`HTTP ${res.status}`);

      // streaming response
      setMessages(m=>[...m,{role:"ai",text:"",streaming:true}]);
      setHappening(h=>({...h, phase:"generating"}));
      const reader  = res.body.getReader();
      const decoder = new TextDecoder();
      let full = "", tokens = 0;

      while (true) {
        const {done,value} = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value);
        const lines = chunk.split("\n").filter(l=>l.startsWith("data: "));
        for (const line of lines) {
          const data = line.slice(6);
          if (data==="[DONE]") continue;
          try {
            const j = JSON.parse(data);
            const delta = j.choices?.[0]?.delta?.content || "";
            full += delta;
            tokens++;
            setTokenCount(t=>t+1);
            setMessages(m=>[...m.slice(0,-1),{role:"ai",text:full,streaming:true}]);
            setHappening(h=>({...h,tokens:tokens}));
          } catch(e){}
        }
      }
      setMessages(m=>[...m.slice(0,-1),{role:"ai",text:full,streaming:false,saveable:true}]);
      setHappening(h=>({...h,phase:"done",tokens}));
    } catch(e) {
      if (e.name!=="AbortError")
        setMessages(m=>[...m,{role:"ai",text:`✗ ${e.message}`}]);
    }
    setStreaming(false);
  };

  const saveToBrain = (text) => {
    const entry = { id:Date.now(), text, source:"quick-study", savedAt:new Date().toISOString() };
    const existing = JSON.parse(localStorage.getItem("oni_brain")||"[]");
    localStorage.setItem("oni_brain", JSON.stringify([...existing, entry]));
    setSaveQueue(q=>[...q, entry.id]);
    setTimeout(()=>setSaveQueue(q=>q.filter(i=>i!==entry.id)), 2000);
  };

  return (
    <div className="qs-layout">
      {/* CHAT */}
      <div className="qs-chat">
        <div className="qs-messages">
          {messages.map((m,i)=>(
            <div key={i} className={`qs-msg qs-msg-${m.role}`}>
              <div className="qs-msg-sender">{m.role==="ai"?"ONI RESEARCH":"YOU"}</div>
              <div className="qs-msg-text">{m.text}{m.streaming&&<span className="qs-cursor">▌</span>}</div>
              {m.saveable && !m.saved && (
                <button className="btn-save-brain" onClick={()=>{saveToBrain(m.text);m.saved=true;}}>
                  🧠 SAVE TO BRAIN
                </button>
              )}
            </div>
          ))}
          <div ref={endRef}/>
        </div>
        <div className="qs-input-row">
          <textarea
            className="qs-input"
            value={input}
            onChange={e=>setInput(e.target.value)}
            onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}}
            placeholder={assign?.model ? "Ask anything to study..." : "Configure a model in Settings first..."}
            disabled={streaming}
          />
          <button className="btn-qs-send" onClick={send} disabled={streaming||!input.trim()}>
            {streaming ? "▌" : "SEND ▶"}
          </button>
        </div>
      </div>

      {/* WHAT'S HAPPENING */}
      <div className="qs-happening">
        <div className="qs-happening-title">⚡ WHAT'S HAPPENING</div>
        {!assign?.model ? (
          <div className="qs-happening-body">
            <div className="whats-item warn">No model configured</div>
            <button className="btn-configure-model" onClick={goSettings}>⚙ OPEN SETTINGS</button>
          </div>
        ) : (
          <div className="qs-happening-body">
            <div className="whats-item">
              <span className="whats-label">MODEL</span>
              <span className="whats-val yellow">{assign.model}</span>
            </div>
            <div className="whats-item">
              <span className="whats-label">RUNNING</span>
              <span className={`whats-val ${conn?.type==="local"?"green":"pink"}`}>
                {conn?.type==="local" ? "🖥 LOCAL — YOUR MACHINE" : "☁ CLOUD API"}
              </span>
            </div>
            {conn?.type==="local" && (
              <div className="whats-item">
                <span className="whats-label">DATA LEAVING</span>
                <span className="whats-val green">NONE ✓</span>
              </div>
            )}
            <div className="whats-item">
              <span className="whats-label">STATUS</span>
              <span className="whats-val">{happening?.phase?.toUpperCase()||"IDLE"}</span>
            </div>
            {happening?.tokens > 0 && (
              <div className="whats-item">
                <span className="whats-label">TOKENS</span>
                <span className="whats-val">{tokenCount}</span>
              </div>
            )}
            <div className="whats-divider"/>
            <div className="whats-explainer">
              <div className="whats-explainer-title">HOW IT WORKS</div>
              <p>Your question is tokenized — split into word fragments — then passed to the model running {conn?.type==="local"?"on your CPU/GPU":"via API"}.</p>
              <p>The model predicts the next token one at a time based on patterns learned during training. That's the blinking cursor you see — each flash is a new token being generated.</p>
              {conn?.type==="local" && <p className="whats-highlight">No company sees your questions. This is yours.</p>}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════
// DEEP RESEARCH
// ═══════════════════════════════════════════════════════════════════
function DeepResearch({ conn, assign, goSettings }) {
  const [topic,       setTopic]       = useState("");
  const [rounds,      setRounds]      = useState(3);
  const [saveBrain,   setSaveBrain]   = useState(true);
  const [running,     setRunning]     = useState(false);
  const [results,     setResults]     = useState([]);   // {roleId, content, summary}
  const [activeRole,  setActiveRole]  = useState(null);
  const [activeRound, setActiveRound] = useState(0);
  const [liveText,    setLiveText]    = useState("");
  const [done,        setDone]        = useState(false);
  const [happening,   setHappening]   = useState(null);
  const outputRef = useRef(null);

  useEffect(()=>{ outputRef.current?.scrollTo(0,outputRef.current.scrollHeight); },[liveText,results]);

  const callModel = async (prompt) => {
    if (!conn || !assign?.model) throw new Error("No model configured");
    const endpoint = conn.type==="local"
      ? `${conn.url}/v1/chat/completions`
      : `${conn.url}/chat/completions`;

    const res = await fetch(endpoint, {
      method:"POST",
      headers:{ "Content-Type":"application/json", ...(conn.apiKey?{"Authorization":`Bearer ${conn.apiKey}`}:{}) },
      body: JSON.stringify({
        model:assign.model,
        messages:[{ role:"user", content:prompt }],
        stream:true, temperature:0.8,
      }),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);

    const reader  = res.body.getReader();
    const decoder = new TextDecoder();
    let full = "";
    while (true) {
      const {done,value} = await reader.read();
      if (done) break;
      const lines = decoder.decode(value).split("\n").filter(l=>l.startsWith("data: "));
      for (const line of lines) {
        const data = line.slice(6);
        if (data==="[DONE]") continue;
        try {
          const delta = JSON.parse(data).choices?.[0]?.delta?.content||"";
          full += delta;
          setLiveText(full);
          setHappening(h=>({...h,tokens:(h?.tokens||0)+1}));
        } catch(e){}
      }
    }
    return full;
  };

  const runResearch = async () => {
    if (!topic.trim() || !assign?.model) return;
    setRunning(true); setResults([]); setDone(false); setLiveText(""); setActiveRound(0);

    const history = [];
    // Determine which roles to use based on rounds
    const roleSequence = [];
    for (let r=0; r<rounds; r++) {
      roleSequence.push(COUNCIL_ROLES[Math.min(r, COUNCIL_ROLES.length-1)]);
    }
    // Always end with archivist if saveBrain is on
    if (saveBrain && roleSequence[roleSequence.length-1].id !== "archivist") {
      roleSequence.push(COUNCIL_ROLES[3]); // archivist
    }

    try {
      for (let i=0; i<roleSequence.length; i++) {
        const role = roleSequence[i];
        setActiveRole(role.id);
        setActiveRound(i+1);
        setLiveText("");
        setHappening({ phase:`Round ${i+1} — ${role.name}`, model:assign.model, local:conn?.type==="local", tokens:0 });

        const prompt  = role.prompt(topic, i+1, history, false);
        const content = await callModel(prompt);
        const summary = content.slice(0,200)+"...";

        history.push({ role:role.name, summary:content });
        setResults(prev=>[...prev,{ roleId:role.id, content, summary }]);
        setLiveText("");

        // save archivist output to brain
        if (role.id==="archivist" && saveBrain) {
          const entry = { id:Date.now(), text:content, topic, source:"deep-research", savedAt:new Date().toISOString() };
          const existing = JSON.parse(localStorage.getItem("oni_brain")||"[]");
          localStorage.setItem("oni_brain", JSON.stringify([...existing, entry]));
        }
      }
      setDone(true);
      setHappening(h=>({...h,phase:"COMPLETE"}));
    } catch(e) {
      setLiveText(`\n✗ Error: ${e.message}`);
    }
    setRunning(false); setActiveRole(null);
  };

  const exportPDF = async () => {
    try {
      await generatePDF(topic, results, assign?.model||"Unknown");
    } catch(e) {
      alert("PDF export failed: "+e.message+"\n\nMake sure jspdf is installed: npm install jspdf");
    }
  };

  return (
    <div className="dr-layout">

      {/* CONFIG BAR */}
      <div className="dr-config">
        <div className="dr-config-row">
          <input
            className="dr-topic-input"
            value={topic}
            onChange={e=>setTopic(e.target.value)}
            placeholder="Research topic... e.g. 'quantum computing and cryptography'"
            disabled={running}
            onKeyDown={e=>{if(e.key==="Enter")runResearch();}}
          />
          <div className="dr-config-controls">
            <label className="dr-config-label">ROUNDS</label>
            <input type="number" className="dr-rounds-input" value={rounds} min={1} max={8}
              onChange={e=>setRounds(Math.max(1,Math.min(8,parseInt(e.target.value)||1)))}
              disabled={running}/>
            <label className={`dr-toggle${saveBrain?" on":""}`}>
              <input type="checkbox" checked={saveBrain} onChange={e=>setSaveBrain(e.target.checked)} disabled={running}/>
              SAVE TO BRAIN
            </label>
            {!running
              ? <button className="btn-dr-start" onClick={runResearch} disabled={!topic.trim()||!assign?.model}>
                  ▶ START RESEARCH
                </button>
              : <button className="btn-dr-stop" onClick={()=>setRunning(false)}>■ STOP</button>
            }
          </div>
        </div>
        {!assign?.model && (
          <div className="dr-no-model">⚠ No model set — <button className="cam-link-btn" onClick={goSettings}>open Settings</button></div>
        )}
      </div>

      {/* MAIN BODY */}
      <div className="dr-body">

        {/* COUNCIL PIPELINE */}
        <div className="dr-pipeline">
          <div className="dr-panel-title">COUNCIL PIPELINE</div>

          {/* role cards */}
          {COUNCIL_ROLES.map((role,i)=>{
            const result  = results.find(r=>r.roleId===role.id);
            const isActive = activeRole===role.id;
            const isDone   = !!result;
            return (
              <div key={role.id} className={`dr-role-card ${isActive?"active":""} ${isDone?"done":""}`}>
                <div className="dr-role-top">
                  <span className="dr-role-icon">{role.icon}</span>
                  <div>
                    <div className={`dr-role-name color-${role.color}`}>{role.name}</div>
                    <div className="dr-role-status">
                      {isActive ? <><span className="dr-spinner"/>RUNNING...</>
                       : isDone ? "✓ COMPLETE"
                       : "WAITING"}
                    </div>
                  </div>
                </div>
                {isDone && (
                  <div className="dr-role-summary">{result.content.slice(0,120)}...</div>
                )}
              </div>
            );
          })}

          {/* export */}
          {done && (
            <button className="btn-dr-export" onClick={exportPDF}>
              ↓ EXPORT PDF REPORT
            </button>
          )}

          {/* what's happening */}
          {happening && (
            <div className="dr-happening">
              <div className="dr-happening-label">⚡ {happening.phase}</div>
              <div className="dr-happening-detail">{assign?.model}</div>
              {happening.local && <div className="dr-happening-local">🖥 LOCAL — NO DATA LEAVING</div>}
              {happening.tokens>0 && <div className="dr-happening-tokens">{happening.tokens} tokens</div>}
            </div>
          )}
        </div>

        {/* LIVE OUTPUT */}
        <div className="dr-output" ref={outputRef}>
          <div className="dr-panel-title">
            LIVE OUTPUT
            {activeRole && <span className="dr-output-role">
              {COUNCIL_ROLES.find(r=>r.id===activeRole)?.icon} {COUNCIL_ROLES.find(r=>r.id===activeRole)?.name}
            </span>}
          </div>

          {results.length===0 && !liveText && !running && (
            <div className="dr-output-empty">
              <div className="dr-output-empty-icon">🔬</div>
              <div>Enter a topic and hit START RESEARCH.</div>
              <div className="dr-output-empty-sub">
                The council will run {rounds} round{rounds!==1?"s":""} of analysis,
                each with a different perspective: Researcher → Critic → Synthesizer
                {saveBrain?" → Archivist (saved to Brain)":""}.
              </div>
            </div>
          )}

          {results.map((r,i)=>{
            const role = COUNCIL_ROLES.find(c=>c.id===r.roleId);
            return (
              <div key={i} className="dr-result-block">
                <div className={`dr-result-header color-${role?.color||"green"}`}>
                  {role?.icon} ROUND {i+1} — {role?.name}
                </div>
                <div className="dr-result-content">{r.content}</div>
              </div>
            );
          })}

          {liveText && (
            <div className="dr-result-block live">
              <div className={`dr-result-header color-${COUNCIL_ROLES.find(r=>r.id===activeRole)?.color||"yellow"}`}>
                {COUNCIL_ROLES.find(r=>r.id===activeRole)?.icon} ROUND {activeRound} — {COUNCIL_ROLES.find(r=>r.id===activeRole)?.name}
                <span className="dr-live-badge">LIVE</span>
              </div>
              <div className="dr-result-content">{liveText}<span className="qs-cursor">▌</span></div>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════
// BRAIN / MEMORY
// ═══════════════════════════════════════════════════════════════════
function BrainMemory({ conn, assign, goSettings }) {
  const [memories,   setMemories]   = useState(()=>JSON.parse(localStorage.getItem("oni_brain")||"[]"));
  const [selected,   setSelected]   = useState(null);
  const [chromaUrl,  setChromaUrl]  = useState("http://localhost:8000");
  const [chromaStatus, setChromaStatus] = useState("unchecked");
  const [collections, setCollections]  = useState([]);
  const [addText,    setAddText]    = useState("");

  const refresh = () => setMemories(JSON.parse(localStorage.getItem("oni_brain")||"[]"));

  const deleteMemory = (id) => {
    const next = memories.filter(m=>m.id!==id);
    localStorage.setItem("oni_brain", JSON.stringify(next));
    setMemories(next);
    if (selected?.id===id) setSelected(null);
  };

  const addManual = () => {
    if (!addText.trim()) return;
    const entry = { id:Date.now(), text:addText, source:"manual", savedAt:new Date().toISOString() };
    const next  = [...memories, entry];
    localStorage.setItem("oni_brain", JSON.stringify(next));
    setMemories(next);
    setAddText("");
  };

  const clearAll = () => {
    if (!confirm("Clear all brain memory? This cannot be undone.")) return;
    localStorage.setItem("oni_brain","[]");
    setMemories([]);
    setSelected(null);
  };

  const testChroma = async () => {
    setChromaStatus("testing");
    try {
      const res = await fetch(`${chromaUrl}/api/v1/collections`, { signal:AbortSignal.timeout(3000) });
      if (res.ok) {
        const data = await res.json();
        setCollections(data||[]);
        setChromaStatus("connected");
      } else throw new Error();
    } catch { setChromaStatus("error"); }
  };

  const pushToChroma = async (memory) => {
    try {
      // ensure collection exists
      await fetch(`${chromaUrl}/api/v1/collections`, {
        method:"POST", headers:{"Content-Type":"application/json"},
        body:JSON.stringify({ name:"oni_research", metadata:{ description:"ONI research memories" } })
      });
      // add document
      await fetch(`${chromaUrl}/api/v1/collections/oni_research/add`, {
        method:"POST", headers:{"Content-Type":"application/json"},
        body:JSON.stringify({
          documents:[memory.text],
          ids:[`oni_${memory.id}`],
          metadatas:[{ source:memory.source, savedAt:memory.savedAt, topic:memory.topic||"" }]
        })
      });
      alert("✓ Pushed to ChromaDB");
    } catch(e) { alert("✗ ChromaDB error: "+e.message); }
  };

  return (
    <div className="brain-layout">

      {/* LEFT: memory list */}
      <div className="brain-list">
        <div className="brain-list-header">
          <span className="dr-panel-title">STORED MEMORIES ({memories.length})</span>
          <button className="btn-brain-clear" onClick={clearAll}>✕ CLEAR ALL</button>
        </div>

        <div className="brain-add-row">
          <input className="brain-add-input" value={addText} onChange={e=>setAddText(e.target.value)}
            placeholder="Manually add a memory..." onKeyDown={e=>{if(e.key==="Enter")addManual();}}/>
          <button className="btn-brain-add" onClick={addManual}>+ ADD</button>
        </div>

        <div className="brain-entries">
          {memories.length===0 && (
            <div className="brain-empty">No memories yet. Use Quick Study or Deep Research and hit "Save to Brain".</div>
          )}
          {memories.map(m=>(
            <div key={m.id} className={`brain-entry${selected?.id===m.id?" selected":""}`} onClick={()=>setSelected(m)}>
              <div className="brain-entry-source">{m.source} · {new Date(m.savedAt).toLocaleDateString()}</div>
              <div className="brain-entry-preview">{m.text.slice(0,80)}...</div>
              <div className="brain-entry-actions">
                {chromaStatus==="connected" && (
                  <button className="btn-brain-push" onClick={e=>{e.stopPropagation();pushToChroma(m);}}>→ CHROMA</button>
                )}
                <button className="btn-brain-del" onClick={e=>{e.stopPropagation();deleteMemory(m.id);}}>✕</button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* RIGHT: explainer + selected + chromadb */}
      <div className="brain-right">

        {/* Selected memory */}
        {selected && (
          <div className="brain-selected">
            <div className="brain-selected-header">
              <span className="dr-panel-title">MEMORY DETAIL</span>
              <span className="brain-selected-meta">{selected.source} · {new Date(selected.savedAt).toLocaleString()}</span>
            </div>
            <div className="brain-selected-text">{selected.text}</div>
          </div>
        )}

        {/* HOW IT WORKS explainer */}
        <div className="brain-explainer">
          <div className="brain-explainer-title">🧠 HOW AI MEMORY WORKS</div>
          <div className="brain-explainer-body">
            <p>When you save something to Brain, it gets stored as text here in localStorage — simple and local.</p>
            <p>When ChromaDB is connected, each memory gets converted to a <strong>vector embedding</strong> — a list of ~1500 numbers that represent the meaning of the text in multi-dimensional space.</p>
            <div className="brain-vector-demo">
              <div className="brain-vector-label">Example embedding (1536 dimensions):</div>
              <div className="brain-vector-numbers">
                {Array.from({length:24},(_,i)=>(Math.random()*2-1).toFixed(3)).join("  ")}  ...
              </div>
            </div>
            <p>When you ask a question, your query becomes a vector too. ChromaDB finds the memories whose vectors are <em>closest</em> in that space — that's semantic similarity search.</p>
            <p>Those relevant memories get injected into the model's context window before it answers. The model didn't "learn" from your data — it just has more context. This is called <strong>RAG: Retrieval Augmented Generation</strong>.</p>
            <div className="brain-rag-diagram">
              <span className="brain-rag-step">YOUR QUERY</span>
              <span className="brain-rag-arrow">→</span>
              <span className="brain-rag-step">EMBED</span>
              <span className="brain-rag-arrow">→</span>
              <span className="brain-rag-step">SEARCH CHROMA</span>
              <span className="brain-rag-arrow">→</span>
              <span className="brain-rag-step">INJECT CONTEXT</span>
              <span className="brain-rag-arrow">→</span>
              <span className="brain-rag-step green">MODEL RESPONDS</span>
            </div>
            <p className="brain-explainer-highlight">Your data never leaves your machine. ChromaDB runs in your Docker container.</p>
          </div>
        </div>

        {/* CHROMADB CONNECTION */}
        <div className="brain-chroma">
          <div className="brain-chroma-header">
            <span className="dr-panel-title">CHROMADB</span>
            <span className={`conn-status status-${chromaStatus}`}>{chromaStatus.toUpperCase()}</span>
          </div>
          <div className="brain-chroma-row">
            <input className="settings-input" value={chromaUrl} onChange={e=>setChromaUrl(e.target.value)} placeholder="http://localhost:8000"/>
            <button className="btn-sa green" onClick={testChroma}>TEST</button>
          </div>
          {chromaStatus==="error" && (
            <div className="brain-chroma-hint">
              Make sure ChromaDB is running in Docker:<br/>
              <code>docker run -p 8000:8000 chromadb/chroma</code>
            </div>
          )}
          {chromaStatus==="connected" && collections.length>0 && (
            <div className="brain-collections">
              <div className="brain-col-label">COLLECTIONS ({collections.length})</div>
              {collections.map(c=>(
                <div key={c.name} className="brain-collection-row">
                  <span>{c.name}</span>
                  <span className="brain-col-count">{c.count||0} docs</span>
                </div>
              ))}
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
